version: '3'
services:
  db:
    image: mysql/mysql-server:5.5
    ports:
        - '${MYSQL_LOCAL_PORT}:3306'
    environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql:cached
  php:
    build: build/php
#    image: pmmresende/ezpublish-php-legacy
    expose:
      - '9000'
    links:
      - db
    volumes:
      - ezpublish-sync:/var/www/html/ezpublish:rw
  web:
    build: build/nginx
#    image: pmmresende/ezpublish-nginx-legacy
    ports:
        - '${LOCAL_WEB_PORT}:80'
    links:
        - php
        - db
    volumes:
        - ./log:/var/log/nginx:cached
        - ./ezpublish:/var/www/html/ezpublish:cached
