version: '2'
services:
  db:
    image: mysql/mysql-server:5.5
    ports:
        - '${MYSQL_LOCAL_PORT}:3306'
    environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    image: php:${PHP_VERSION}-fpm
    expose:
      - '9000'
    links:
      - db
    volumes:
      - ./ezpublish:/var/www/html/ezpublish
  web:
    build: build/nginx
    ports:
        - '${LOCAL_WEB_PORT}:80'
    links:
        - php
        - db
    volumes:
        - /tmp:/var/log/nginx
        - ./ezpublish:/var/www/html/ezpublish
